name: Build Docker image
on:
  push:
    branches: [ '*' ]
    paths-ignore:
      - "**/docs/**"
      - "**.md"
  pull_request:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USER: cargogenerate
      DOCKERHUB_IMAGE: cargo-generate-action
    steps:
      # Check out code
      - name: Checkout
        uses: actions/checkout@v3
      # This is the a separate action that sets up buildx runner
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # And make it available for the builds
      - name: Build only
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
